"""Add created_at field to Task

Revision ID: 029f1f873096
Revises: 
Create Date: 2025-01-27 08:39:54.988618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029f1f873096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
